import type { Metadata } from "next";
import { Bai_Jamjuree, Cascadia_Code } from "next/font/google";
import "./globals.scss";
import Navigation from "./navigation";

const baiJamjuree = Bai_Jamjuree({
  weight: "700",
  subsets: ["latin"]
})
const cascadiaCode = Cascadia_Code({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Brett Anda's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${baiJamjuree} ${cascadiaCode} antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
